services:
  # Main Application
  - type: web
    name: swarm-mcp-app
    runtime: docker
    dockerfilePath: ./deployment/Dockerfile
    dockerContext: .
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: swarm-db
          property: connectionString
      - key: REDIS_URL
        value: redis://swarm-redis:6379
      - key: SECRET_KEY
        generateValue: true
      - key: OPENROUTER_API_KEY
        sync: false  # Set in dashboard
      - key: MAILGUN_API_KEY
        sync: false  # Set in dashboard
      - key: MAILGUN_DOMAIN
        sync: false  # Set in dashboard  
      - key: MAILGUN_SIGNING_KEY
        sync: false  # Set in dashboard
    autoDeploy: false
    healthCheckPath: /health

  # Background Worker
  - type: worker
    name: swarm-celery-worker
    runtime: docker
    dockerfilePath: ./deployment/Dockerfile
    dockerContext: .
    dockerCommand: celery -A tasks.agent_tasks worker --loglevel=info
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: swarm-db
          property: connectionString
      - key: REDIS_URL
        value: redis://swarm-redis:6379

  # Redis Cache
  - type: pserv
    name: swarm-redis
    runtime: docker
    repo: https://github.com/render-examples/redis
    autoDeploy: false
    disk:
      name: redis-data
      mountPath: /data
      sizeGB: 1

databases:
  - name: swarm-db
    plan: free  # Free tier for development, upgrade to standard for production
    postgresMajorVersion: 15