services:
  # Main Application
  - type: web
    name: swarm-mcp-app
    runtime: docker
    dockerfilePath: ./deployment/Dockerfile
    dockerContext: .
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: swarm-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: pserv
          name: swarm-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: OPENROUTER_API_KEY
        sync: false  # Set in dashboard
      - key: MAILGUN_API_KEY
        sync: false  # Set in dashboard
      - key: MAILGUN_DOMAIN
        sync: false  # Set in dashboard
      - key: MAILGUN_SIGNING_KEY
        sync: false  # Set in dashboard
      - key: SENTRY_DSN
        value: ""  # Optional - set in dashboard if needed
      - key: NODE_ENV
        value: production
      - key: DISABLE_MCP_FILESYSTEM
        value: "false"  # Enable MCP filesystem server for full functionality
    autoDeploy: false
    healthCheckPath: /api/monitoring/ready

  # Background Worker
  - type: worker
    name: swarm-celery-worker
    runtime: docker
    dockerfilePath: ./deployment/Dockerfile
    dockerContext: .
    dockerCommand: celery -A app.celery worker --loglevel=info
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: swarm-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: pserv
          name: swarm-redis
          property: connectionString

  # Redis Cache
  - type: pserv
    name: swarm-redis
    runtime: docker
    repo: https://github.com/render-examples/redis
    autoDeploy: false
    disk:
      name: redis-data
      mountPath: /data
      sizeGB: 1

databases:
  - name: swarm-db
    plan: free  # Free tier for development, upgrade to standard for production
    postgresMajorVersion: 15